version: '3.8'

services:
  app:
    build: .
    container_name: angelone-mf-portfolio
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./angelone.sqlite3:/app/angelone.sqlite3
      - ./browser_profile:/app/browser_profile
      - .:/app/data
    environment:
      - PORT=8000
